import type { Exercise } from "fitness/utils/types";

export type ExerciseCatalogItem = Omit<Exercise, "id">;

export const exerciseCatalog: ExerciseCatalogItem[] = [
  // =========================================================
  // CHEST
  // =========================================================

  {
    name: "Barbell Bench Press",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Mid chest",
    isCompound: true,
  },
  {
    name: "Incline Barbell Bench Press",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Upper chest",
    isCompound: true,
  },
  {
    name: "Decline Barbell Bench Press",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Lower chest",
    isCompound: true,
  },
  {
    name: "Dumbbell Bench Press",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Mid chest",
    isCompound: true,
  },
  {
    name: "Incline Dumbbell Press",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Upper chest",
    isCompound: true,
  },
  {
    name: "Decline Dumbbell Press",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Lower chest",
    isCompound: true,
  },
  {
    name: "Dumbbell Floor Press",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Mid chest",
    isCompound: true,
  },
  {
    name: "Dumbbell Squeeze Press",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Inner chest",
    isCompound: true,
  },
  {
    name: "Machine Chest Press",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Chest",
    region: "Mid chest",
    isCompound: true,
  },
  {
    name: "Incline Machine Chest Press",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Chest",
    region: "Upper chest",
    isCompound: true,
  },
  {
    name: "Decline Machine Chest Press",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Chest",
    region: "Lower chest",
    isCompound: true,
  },
  {
    name: "Smith Machine Bench Press",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Chest",
    region: "Mid chest",
    isCompound: true,
  },
  {
    name: "Smith Machine Incline Press",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Chest",
    region: "Upper chest",
    isCompound: true,
  },
  {
    name: "Push-Up",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Chest",
    region: "Mid chest",
    isCompound: true,
  },
  {
    name: "Wide-Grip Push-Up",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Chest",
    region: "Outer chest",
    isCompound: true,
  },
  {
    name: "Incline Push-Up",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Chest",
    region: "Lower chest",
    isCompound: true,
  },
  {
    name: "Decline Push-Up",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Chest",
    region: "Upper chest",
    isCompound: true,
  },
  {
    name: "Diamond Push-Up",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Chest",
    region: "Inner chest",
    isCompound: true,
  },
  {
    name: "Chest Dip",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Chest",
    region: "Lower chest",
    isCompound: true,
  },
  {
    name: "Dumbbell Fly",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Mid chest",
    isCompound: false,
  },
  {
    name: "Incline Dumbbell Fly",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Upper chest",
    isCompound: false,
  },
  {
    name: "Decline Dumbbell Fly",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Lower chest",
    isCompound: false,
  },
  {
    name: "Cable Fly",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Chest",
    region: "Mid chest",
    isCompound: false,
  },
  {
    name: "Low-to-High Cable Fly",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Chest",
    region: "Upper chest",
    isCompound: false,
  },
  {
    name: "High-to-Low Cable Fly",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Chest",
    region: "Lower chest",
    isCompound: false,
  },
  {
    name: "Single-Arm Cable Fly",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Chest",
    region: "Chest",
    isCompound: false,
  },
  {
    name: "Pec Deck Fly",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Chest",
    region: "Chest",
    isCompound: false,
  },
  {
    name: "Kettlebell Floor Press",
    equipment: "KETTLEBELL",
    movement: "PUSH",
    category: "Chest",
    region: "Mid chest",
    isCompound: true,
  },

  // =========================================================
  // BACK
  // =========================================================

  {
    name: "Conventional Deadlift",
    equipment: "BARBELL",
    movement: "HINGE",
    category: "Back",
    region: "Total back",
    isCompound: true,
  },
  {
    name: "Sumo Deadlift",
    equipment: "BARBELL",
    movement: "HINGE",
    category: "Back",
    region: "Lower back",
    isCompound: true,
  },
  {
    name: "Rack Pull",
    equipment: "BARBELL",
    movement: "HINGE",
    category: "Back",
    region: "Upper and lower back",
    isCompound: true,
  },
  {
    name: "Barbell Row",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Back",
    region: "Middle back",
    isCompound: true,
  },
  {
    name: "Pendlay Row",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Back",
    region: "Middle back",
    isCompound: true,
  },
  {
    name: "Underhand Barbell Row",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Back",
    region: "Lower lats",
    isCompound: true,
  },
  {
    name: "T-Bar Row",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Back",
    region: "Middle back",
    isCompound: true,
  },
  {
    name: "Meadows Row",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Back",
    region: "Lats",
    isCompound: true,
  },
  {
    name: "Single-Arm Dumbbell Row",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Back",
    region: "Lats",
    isCompound: true,
  },
  {
    name: "Chest-Supported Dumbbell Row",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Back",
    region: "Middle back",
    isCompound: true,
  },
  {
    name: "Dumbbell Pullover",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Back",
    region: "Lats",
    isCompound: false,
  },
  {
    name: "Kettlebell Row",
    equipment: "KETTLEBELL",
    movement: "PULL",
    category: "Back",
    region: "Lats",
    isCompound: true,
  },
  {
    name: "Pull-Up",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Back",
    region: "Lats",
    isCompound: true,
  },
  {
    name: "Wide-Grip Pull-Up",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Back",
    region: "Upper lats",
    isCompound: true,
  },
  {
    name: "Neutral-Grip Pull-Up",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Back",
    region: "Lats",
    isCompound: true,
  },
  {
    name: "Chin-Up",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Back",
    region: "Lower lats",
    isCompound: true,
  },
  {
    name: "Inverted Row",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Back",
    region: "Middle back",
    isCompound: true,
  },
  {
    name: "Lat Pulldown",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Back",
    region: "Lats",
    isCompound: true,
  },
  {
    name: "Wide-Grip Lat Pulldown",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Back",
    region: "Upper lats",
    isCompound: true,
  },
  {
    name: "Close-Grip Lat Pulldown",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Back",
    region: "Lower lats",
    isCompound: true,
  },
  {
    name: "Underhand Lat Pulldown",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Back",
    region: "Lower lats",
    isCompound: true,
  },
  {
    name: "Single-Arm Lat Pulldown",
    equipment: "CABLE",
    movement: "PULL",
    category: "Back",
    region: "Lats",
    isCompound: true,
  },
  {
    name: "Seated Cable Row",
    equipment: "CABLE",
    movement: "PULL",
    category: "Back",
    region: "Middle back",
    isCompound: true,
  },
  {
    name: "Wide-Grip Cable Row",
    equipment: "CABLE",
    movement: "PULL",
    category: "Back",
    region: "Upper back",
    isCompound: true,
  },
  {
    name: "Single-Arm Cable Row",
    equipment: "CABLE",
    movement: "PULL",
    category: "Back",
    region: "Lats",
    isCompound: true,
  },
  {
    name: "Straight-Arm Cable Pulldown",
    equipment: "CABLE",
    movement: "PULL",
    category: "Back",
    region: "Lats",
    isCompound: false,
  },
  {
    name: "Machine Row",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Back",
    region: "Middle back",
    isCompound: true,
  },
  {
    name: "Chest-Supported Machine Row",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Back",
    region: "Middle back",
    isCompound: true,
  },
  {
    name: "Machine Pullover",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Back",
    region: "Lats",
    isCompound: false,
  },
  {
    name: "Back Extension",
    equipment: "BODYWEIGHT",
    movement: "HINGE",
    category: "Back",
    region: "Lower back",
    isCompound: false,
  },
  {
    name: "Weighted Back Extension",
    equipment: "DUMBBELL",
    movement: "HINGE",
    category: "Back",
    region: "Lower back",
    isCompound: false,
  },
  {
    name: "Superman Hold",
    equipment: "BODYWEIGHT",
    movement: "ISOMETRIC",
    category: "Back",
    region: "Lower back",
    isCompound: false,
  },

  // =========================================================
  // SHOULDERS
  // =========================================================

  {
    name: "Barbell Overhead Press",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: true,
  },
  {
    name: "Seated Barbell Shoulder Press",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: true,
  },
  {
    name: "Behind-the-Neck Press",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front and side delts",
    isCompound: true,
  },
  {
    name: "Dumbbell Shoulder Press",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: true,
  },
  {
    name: "Seated Dumbbell Shoulder Press",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: true,
  },
  {
    name: "Arnold Press",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front and side delts",
    isCompound: true,
  },
  {
    name: "Single-Arm Dumbbell Shoulder Press",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: true,
  },
  {
    name: "Kettlebell Shoulder Press",
    equipment: "KETTLEBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: true,
  },
  {
    name: "Machine Shoulder Press",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: true,
  },
  {
    name: "Smith Machine Shoulder Press",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: true,
  },
  {
    name: "Pike Push-Up",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: true,
  },
  {
    name: "Handstand Push-Up",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: true,
  },
  {
    name: "Dumbbell Lateral Raise",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Side delts",
    isCompound: false,
  },
  {
    name: "Seated Dumbbell Lateral Raise",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Side delts",
    isCompound: false,
  },
  {
    name: "Lean-Away Dumbbell Lateral Raise",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Side delts",
    isCompound: false,
  },
  {
    name: "Cable Lateral Raise",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Shoulders",
    region: "Side delts",
    isCompound: false,
  },
  {
    name: "Single-Arm Cable Lateral Raise",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Shoulders",
    region: "Side delts",
    isCompound: false,
  },
  {
    name: "Machine Lateral Raise",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Shoulders",
    region: "Side delts",
    isCompound: false,
  },
  {
    name: "Dumbbell Front Raise",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: false,
  },
  {
    name: "Barbell Front Raise",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: false,
  },
  {
    name: "Cable Front Raise",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Shoulders",
    region: "Front delts",
    isCompound: false,
  },
  {
    name: "Dumbbell Rear Delt Fly",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Shoulders",
    region: "Rear delts",
    isCompound: false,
  },
  {
    name: "Reverse Pec Deck",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Shoulders",
    region: "Rear delts",
    isCompound: false,
  },
  {
    name: "Cable Rear Delt Fly",
    equipment: "CABLE",
    movement: "PULL",
    category: "Shoulders",
    region: "Rear delts",
    isCompound: false,
  },
  {
    name: "Face Pull",
    equipment: "CABLE",
    movement: "PULL",
    category: "Shoulders",
    region: "Rear delts",
    isCompound: false,
  },
  {
    name: "Barbell Upright Row",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Shoulders",
    region: "Side delts",
    isCompound: true,
  },
  {
    name: "Dumbbell Upright Row",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Shoulders",
    region: "Side delts",
    isCompound: true,
  },
  {
    name: "Cable Upright Row",
    equipment: "CABLE",
    movement: "PULL",
    category: "Shoulders",
    region: "Side delts",
    isCompound: true,
  },

  // =========================================================
  // BICEPS
  // =========================================================

  {
    name: "Barbell Curl",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Biceps",
    isCompound: false,
  },
  {
    name: "Wide-Grip Barbell Curl",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Short head",
    isCompound: false,
  },
  {
    name: "Close-Grip Barbell Curl",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Long head",
    isCompound: false,
  },
  {
    name: "Reverse Barbell Curl",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Brachialis",
    isCompound: false,
  },
  {
    name: "Barbell Drag Curl",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Long head",
    isCompound: false,
  },
  {
    name: "Dumbbell Bicep Curl",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Biceps",
    isCompound: false,
  },
  {
    name: "Alternating Dumbbell Curl",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Biceps",
    isCompound: false,
  },
  {
    name: "Incline Dumbbell Curl",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Long head",
    isCompound: false,
  },
  {
    name: "Hammer Curl",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Brachialis",
    isCompound: false,
  },
  {
    name: "Cross-Body Hammer Curl",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Brachialis",
    isCompound: false,
  },
  {
    name: "Concentration Curl",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Short head",
    isCompound: false,
  },
  {
    name: "Spider Curl",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Short head",
    isCompound: false,
  },
  {
    name: "Zottman Curl",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Biceps and forearms",
    isCompound: false,
  },
  {
    name: "Dumbbell Preacher Curl",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Biceps",
    region: "Short head",
    isCompound: false,
  },
  {
    name: "Cable Bicep Curl",
    equipment: "CABLE",
    movement: "PULL",
    category: "Biceps",
    region: "Biceps",
    isCompound: false,
  },
  {
    name: "Rope Hammer Curl",
    equipment: "CABLE",
    movement: "PULL",
    category: "Biceps",
    region: "Brachialis",
    isCompound: false,
  },
  {
    name: "Single-Arm Cable Curl",
    equipment: "CABLE",
    movement: "PULL",
    category: "Biceps",
    region: "Biceps",
    isCompound: false,
  },
  {
    name: "High Cable Curl",
    equipment: "CABLE",
    movement: "PULL",
    category: "Biceps",
    region: "Short head",
    isCompound: false,
  },
  {
    name: "Bayesian Cable Curl",
    equipment: "CABLE",
    movement: "PULL",
    category: "Biceps",
    region: "Long head",
    isCompound: false,
  },
  {
    name: "Machine Preacher Curl",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Biceps",
    region: "Short head",
    isCompound: false,
  },
  {
    name: "Machine Bicep Curl",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Biceps",
    region: "Biceps",
    isCompound: false,
  },

  // =========================================================
  // TRICEPS
  // =========================================================

  {
    name: "Close-Grip Bench Press",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Triceps",
    region: "Triceps",
    isCompound: true,
  },
  {
    name: "JM Press",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Triceps",
    region: "Triceps",
    isCompound: true,
  },
  {
    name: "Barbell Skull Crusher",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Triceps",
    region: "Long head",
    isCompound: false,
  },
  {
    name: "Incline Barbell Skull Crusher",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Triceps",
    region: "Long head",
    isCompound: false,
  },
  {
    name: "Dumbbell Skull Crusher",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Triceps",
    region: "Long head",
    isCompound: false,
  },
  {
    name: "Overhead Dumbbell Extension",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Triceps",
    region: "Long head",
    isCompound: false,
  },
  {
    name: "Single-Arm Overhead Dumbbell Extension",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Triceps",
    region: "Long head",
    isCompound: false,
  },
  {
    name: "Dumbbell Tricep Kickback",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Triceps",
    region: "Lateral head",
    isCompound: false,
  },
  {
    name: "Tricep Pushdown",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Triceps",
    region: "Lateral head",
    isCompound: false,
  },
  {
    name: "Rope Tricep Pushdown",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Triceps",
    region: "Lateral head",
    isCompound: false,
  },
  {
    name: "Reverse-Grip Tricep Pushdown",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Triceps",
    region: "Medial head",
    isCompound: false,
  },
  {
    name: "Single-Arm Cable Pushdown",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Triceps",
    region: "Lateral head",
    isCompound: false,
  },
  {
    name: "Cable Overhead Tricep Extension",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Triceps",
    region: "Long head",
    isCompound: false,
  },
  {
    name: "Single-Arm Cable Overhead Extension",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Triceps",
    region: "Long head",
    isCompound: false,
  },
  {
    name: "Cable Tricep Kickback",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Triceps",
    region: "Lateral head",
    isCompound: false,
  },
  {
    name: "Bench Dip",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Triceps",
    region: "Triceps",
    isCompound: true,
  },
  {
    name: "Parallel Bar Dip",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Triceps",
    region: "Triceps",
    isCompound: true,
  },
  {
    name: "Machine Tricep Extension",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Triceps",
    region: "Triceps",
    isCompound: false,
  },
  {
    name: "Assisted Dip Machine",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Triceps",
    region: "Triceps",
    isCompound: true,
  },

  // =========================================================
  // QUADRICEPS
  // =========================================================

  {
    name: "Barbell Back Squat",
    equipment: "BARBELL",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Barbell Front Squat",
    equipment: "BARBELL",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Zercher Squat",
    equipment: "BARBELL",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Hack Squat",
    equipment: "MACHINE",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Pendulum Squat",
    equipment: "MACHINE",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Smith Machine Squat",
    equipment: "MACHINE",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Leg Press",
    equipment: "MACHINE",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Narrow-Stance Leg Press",
    equipment: "MACHINE",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Outer quadriceps",
    isCompound: true,
  },
  {
    name: "Single-Leg Press",
    equipment: "MACHINE",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Leg Extension",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: false,
  },
  {
    name: "Single-Leg Extension",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: false,
  },
  {
    name: "Goblet Squat",
    equipment: "DUMBBELL",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Dumbbell Squat",
    equipment: "DUMBBELL",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Dumbbell Bulgarian Split Squat",
    equipment: "DUMBBELL",
    movement: "LUNGE",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Walking Lunge",
    equipment: "DUMBBELL",
    movement: "LUNGE",
    category: "Quadriceps",
    region: "Quadriceps and glutes",
    isCompound: true,
  },
  {
    name: "Reverse Lunge",
    equipment: "DUMBBELL",
    movement: "LUNGE",
    category: "Quadriceps",
    region: "Quadriceps and glutes",
    isCompound: true,
  },
  {
    name: "Forward Lunge",
    equipment: "DUMBBELL",
    movement: "LUNGE",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Step-Up",
    equipment: "DUMBBELL",
    movement: "LUNGE",
    category: "Quadriceps",
    region: "Quadriceps and glutes",
    isCompound: true,
  },
  {
    name: "Bodyweight Squat",
    equipment: "BODYWEIGHT",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Jump Squat",
    equipment: "BODYWEIGHT",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: true,
  },
  {
    name: "Sissy Squat",
    equipment: "BODYWEIGHT",
    movement: "SQUAT",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: false,
  },
  {
    name: "Wall Sit",
    equipment: "BODYWEIGHT",
    movement: "ISOMETRIC",
    category: "Quadriceps",
    region: "Quadriceps",
    isCompound: false,
  },

  // =========================================================
  // HAMSTRINGS
  // =========================================================

  {
    name: "Romanian Deadlift",
    equipment: "BARBELL",
    movement: "HINGE",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: true,
  },
  {
    name: "Stiff-Leg Deadlift",
    equipment: "BARBELL",
    movement: "HINGE",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: true,
  },
  {
    name: "Good Morning",
    equipment: "BARBELL",
    movement: "HINGE",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: true,
  },
  {
    name: "Dumbbell Romanian Deadlift",
    equipment: "DUMBBELL",
    movement: "HINGE",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: true,
  },
  {
    name: "Single-Leg Romanian Deadlift",
    equipment: "DUMBBELL",
    movement: "HINGE",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: true,
  },
  {
    name: "Kettlebell Romanian Deadlift",
    equipment: "KETTLEBELL",
    movement: "HINGE",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: true,
  },
  {
    name: "Kettlebell Swing",
    equipment: "KETTLEBELL",
    movement: "HINGE",
    category: "Hamstrings",
    region: "Hamstrings and glutes",
    isCompound: true,
  },
  {
    name: "Lying Leg Curl",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: false,
  },
  {
    name: "Seated Leg Curl",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: false,
  },
  {
    name: "Standing Single-Leg Curl",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: false,
  },
  {
    name: "Cable Leg Curl",
    equipment: "CABLE",
    movement: "PULL",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: false,
  },
  {
    name: "Nordic Hamstring Curl",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: false,
  },
  {
    name: "Sliding Leg Curl",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Hamstrings",
    region: "Hamstrings",
    isCompound: false,
  },
  {
    name: "Glute-Ham Raise",
    equipment: "BODYWEIGHT",
    movement: "HINGE",
    category: "Hamstrings",
    region: "Hamstrings and glutes",
    isCompound: true,
  },

  // =========================================================
  // GLUTES
  // =========================================================

  {
    name: "Barbell Hip Thrust",
    equipment: "BARBELL",
    movement: "HINGE",
    category: "Glutes",
    region: "Gluteus maximus",
    isCompound: true,
  },
  {
    name: "Barbell Glute Bridge",
    equipment: "BARBELL",
    movement: "HINGE",
    category: "Glutes",
    region: "Gluteus maximus",
    isCompound: true,
  },
  {
    name: "Dumbbell Hip Thrust",
    equipment: "DUMBBELL",
    movement: "HINGE",
    category: "Glutes",
    region: "Gluteus maximus",
    isCompound: true,
  },
  {
    name: "Dumbbell Glute Bridge",
    equipment: "DUMBBELL",
    movement: "HINGE",
    category: "Glutes",
    region: "Gluteus maximus",
    isCompound: true,
  },
  {
    name: "Single-Leg Hip Thrust",
    equipment: "BODYWEIGHT",
    movement: "HINGE",
    category: "Glutes",
    region: "Gluteus maximus",
    isCompound: true,
  },
  {
    name: "Bodyweight Glute Bridge",
    equipment: "BODYWEIGHT",
    movement: "HINGE",
    category: "Glutes",
    region: "Gluteus maximus",
    isCompound: false,
  },
  {
    name: "Frog Pump",
    equipment: "BODYWEIGHT",
    movement: "HINGE",
    category: "Glutes",
    region: "Gluteus maximus",
    isCompound: false,
  },
  {
    name: "Cable Glute Kickback",
    equipment: "CABLE",
    movement: "HINGE",
    category: "Glutes",
    region: "Gluteus maximus",
    isCompound: false,
  },
  {
    name: "Cable Pull-Through",
    equipment: "CABLE",
    movement: "HINGE",
    category: "Glutes",
    region: "Glutes and hamstrings",
    isCompound: true,
  },
  {
    name: "Cable Hip Abduction",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Glutes",
    region: "Gluteus medius",
    isCompound: false,
  },
  {
    name: "Hip Abduction Machine",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Glutes",
    region: "Gluteus medius",
    isCompound: false,
  },
  {
    name: "Hip Adduction Machine",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Glutes",
    region: "Inner thighs",
    isCompound: false,
  },
  {
    name: "Machine Glute Kickback",
    equipment: "MACHINE",
    movement: "HINGE",
    category: "Glutes",
    region: "Gluteus maximus",
    isCompound: false,
  },
  {
    name: "Donkey Kick",
    equipment: "BODYWEIGHT",
    movement: "HINGE",
    category: "Glutes",
    region: "Gluteus maximus",
    isCompound: false,
  },
  {
    name: "Fire Hydrant",
    equipment: "BODYWEIGHT",
    movement: "ROTATION",
    category: "Glutes",
    region: "Gluteus medius",
    isCompound: false,
  },
  {
    name: "Lateral Lunge",
    equipment: "DUMBBELL",
    movement: "LUNGE",
    category: "Glutes",
    region: "Glutes and inner thighs",
    isCompound: true,
  },
  {
    name: "Curtsy Lunge",
    equipment: "DUMBBELL",
    movement: "LUNGE",
    category: "Glutes",
    region: "Gluteus medius",
    isCompound: true,
  },

  // =========================================================
  // CALVES
  // =========================================================

  {
    name: "Standing Barbell Calf Raise",
    equipment: "BARBELL",
    movement: "PUSH",
    category: "Calves",
    region: "Gastrocnemius",
    isCompound: false,
  },
  {
    name: "Standing Dumbbell Calf Raise",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Calves",
    region: "Gastrocnemius",
    isCompound: false,
  },
  {
    name: "Single-Leg Dumbbell Calf Raise",
    equipment: "DUMBBELL",
    movement: "PUSH",
    category: "Calves",
    region: "Gastrocnemius",
    isCompound: false,
  },
  {
    name: "Standing Bodyweight Calf Raise",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Calves",
    region: "Gastrocnemius",
    isCompound: false,
  },
  {
    name: "Single-Leg Calf Raise",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Calves",
    region: "Gastrocnemius",
    isCompound: false,
  },
  {
    name: "Seated Calf Raise",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Calves",
    region: "Soleus",
    isCompound: false,
  },
  {
    name: "Standing Machine Calf Raise",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Calves",
    region: "Gastrocnemius",
    isCompound: false,
  },
  {
    name: "Leg Press Calf Raise",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Calves",
    region: "Gastrocnemius",
    isCompound: false,
  },
  {
    name: "Smith Machine Calf Raise",
    equipment: "MACHINE",
    movement: "PUSH",
    category: "Calves",
    region: "Gastrocnemius",
    isCompound: false,
  },
  {
    name: "Donkey Calf Raise",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Calves",
    region: "Gastrocnemius",
    isCompound: false,
  },
  {
    name: "Tibialis Raise",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Calves",
    region: "Tibialis anterior",
    isCompound: false,
  },

  // =========================================================
  // ABS AND CORE
  // =========================================================

  {
    name: "Plank",
    equipment: "BODYWEIGHT",
    movement: "ISOMETRIC",
    category: "Abs",
    region: "Total core",
    isCompound: false,
  },
  {
    name: "Side Plank",
    equipment: "BODYWEIGHT",
    movement: "ISOMETRIC",
    category: "Abs",
    region: "Obliques",
    isCompound: false,
  },
  {
    name: "Weighted Plank",
    equipment: "DUMBBELL",
    movement: "ISOMETRIC",
    category: "Abs",
    region: "Total core",
    isCompound: false,
  },
  {
    name: "Crunch",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Abs",
    region: "Upper abs",
    isCompound: false,
  },
  {
    name: "Reverse Crunch",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Abs",
    region: "Lower abs",
    isCompound: false,
  },
  {
    name: "Bicycle Crunch",
    equipment: "BODYWEIGHT",
    movement: "ROTATION",
    category: "Abs",
    region: "Abs and obliques",
    isCompound: false,
  },
  {
    name: "V-Up",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Abs",
    region: "Total abs",
    isCompound: false,
  },
  {
    name: "Sit-Up",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Abs",
    region: "Upper abs",
    isCompound: false,
  },
  {
    name: "Decline Sit-Up",
    equipment: "BODYWEIGHT",
    movement: "PUSH",
    category: "Abs",
    region: "Upper abs",
    isCompound: false,
  },
  {
    name: "Hanging Knee Raise",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Abs",
    region: "Lower abs",
    isCompound: false,
  },
  {
    name: "Hanging Leg Raise",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Abs",
    region: "Lower abs",
    isCompound: false,
  },
  {
    name: "Captain's Chair Knee Raise",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Abs",
    region: "Lower abs",
    isCompound: false,
  },
  {
    name: "Cable Crunch",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Abs",
    region: "Upper abs",
    isCompound: false,
  },
  {
    name: "Standing Cable Crunch",
    equipment: "CABLE",
    movement: "PUSH",
    category: "Abs",
    region: "Upper abs",
    isCompound: false,
  },
  {
    name: "Cable Wood Chop",
    equipment: "CABLE",
    movement: "ROTATION",
    category: "Abs",
    region: "Obliques",
    isCompound: false,
  },
  {
    name: "Cable Side Bend",
    equipment: "CABLE",
    movement: "ROTATION",
    category: "Abs",
    region: "Obliques",
    isCompound: false,
  },
  {
    name: "Dumbbell Side Bend",
    equipment: "DUMBBELL",
    movement: "ROTATION",
    category: "Abs",
    region: "Obliques",
    isCompound: false,
  },
  {
    name: "Russian Twist",
    equipment: "BODYWEIGHT",
    movement: "ROTATION",
    category: "Abs",
    region: "Obliques",
    isCompound: false,
  },
  {
    name: "Dumbbell Russian Twist",
    equipment: "DUMBBELL",
    movement: "ROTATION",
    category: "Abs",
    region: "Obliques",
    isCompound: false,
  },
  {
    name: "Mountain Climber",
    equipment: "BODYWEIGHT",
    movement: "PULL",
    category: "Abs",
    region: "Total core",
    isCompound: true,
  },
  {
    name: "Dead Bug",
    equipment: "BODYWEIGHT",
    movement: "ISOMETRIC",
    category: "Abs",
    region: "Deep core",
    isCompound: false,
  },
  {
    name: "Bird Dog",
    equipment: "BODYWEIGHT",
    movement: "ISOMETRIC",
    category: "Abs",
    region: "Deep core",
    isCompound: false,
  },
  {
    name: "Hollow Body Hold",
    equipment: "BODYWEIGHT",
    movement: "ISOMETRIC",
    category: "Abs",
    region: "Total core",
    isCompound: false,
  },
  {
    name: "Pallof Press",
    equipment: "CABLE",
    movement: "ISOMETRIC",
    category: "Abs",
    region: "Deep core",
    isCompound: false,
  },

  // =========================================================
  // TRAPS
  // =========================================================

  {
    name: "Barbell Shrug",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Traps",
    region: "Upper traps",
    isCompound: false,
  },
  {
    name: "Behind-the-Back Barbell Shrug",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Traps",
    region: "Upper traps",
    isCompound: false,
  },
  {
    name: "Dumbbell Shrug",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Traps",
    region: "Upper traps",
    isCompound: false,
  },
  {
    name: "Kettlebell Shrug",
    equipment: "KETTLEBELL",
    movement: "PULL",
    category: "Traps",
    region: "Upper traps",
    isCompound: false,
  },
  {
    name: "Cable Shrug",
    equipment: "CABLE",
    movement: "PULL",
    category: "Traps",
    region: "Upper traps",
    isCompound: false,
  },
  {
    name: "Machine Shrug",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Traps",
    region: "Upper traps",
    isCompound: false,
  },
  {
    name: "Farmer's Carry",
    equipment: "DUMBBELL",
    movement: "CARRY",
    category: "Traps",
    region: "Upper traps",
    isCompound: true,
  },
  {
    name: "Kettlebell Farmer's Carry",
    equipment: "KETTLEBELL",
    movement: "CARRY",
    category: "Traps",
    region: "Upper traps",
    isCompound: true,
  },

  // =========================================================
  // FOREARMS AND GRIP
  // =========================================================

  {
    name: "Barbell Wrist Curl",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Forearms",
    region: "Forearm flexors",
    isCompound: false,
  },
  {
    name: "Reverse Barbell Wrist Curl",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Forearms",
    region: "Forearm extensors",
    isCompound: false,
  },
  {
    name: "Dumbbell Wrist Curl",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Forearms",
    region: "Forearm flexors",
    isCompound: false,
  },
  {
    name: "Reverse Dumbbell Wrist Curl",
    equipment: "DUMBBELL",
    movement: "PULL",
    category: "Forearms",
    region: "Forearm extensors",
    isCompound: false,
  },
  {
    name: "Behind-the-Back Wrist Curl",
    equipment: "BARBELL",
    movement: "PULL",
    category: "Forearms",
    region: "Forearm flexors",
    isCompound: false,
  },
  {
    name: "Cable Wrist Curl",
    equipment: "CABLE",
    movement: "PULL",
    category: "Forearms",
    region: "Forearm flexors",
    isCompound: false,
  },
  {
    name: "Cable Reverse Wrist Curl",
    equipment: "CABLE",
    movement: "PULL",
    category: "Forearms",
    region: "Forearm extensors",
    isCompound: false,
  },
  {
    name: "Wrist Roller",
    equipment: "MACHINE",
    movement: "PULL",
    category: "Forearms",
    region: "Total forearms",
    isCompound: false,
  },
  {
    name: "Dead Hang",
    equipment: "BODYWEIGHT",
    movement: "ISOMETRIC",
    category: "Forearms",
    region: "Grip",
    isCompound: false,
  },
  {
    name: "Towel Dead Hang",
    equipment: "BODYWEIGHT",
    movement: "ISOMETRIC",
    category: "Forearms",
    region: "Grip",
    isCompound: false,
  },
  {
    name: "Plate Pinch Hold",
    equipment: "BARBELL",
    movement: "ISOMETRIC",
    category: "Forearms",
    region: "Grip",
    isCompound: false,
  },

  // =========================================================
  // FULL BODY
  // =========================================================

  {
    name: "Barbell Clean",
    equipment: "BARBELL",
    movement: "HINGE",
    category: "Full Body",
    region: "Full body",
    isCompound: true,
  },
  {
    name: "Clean and Press",
    equipment: "BARBELL",
    movement: "HINGE",
    category: "Full Body",
    region: "Full body",
    isCompound: true,
  },
  {
    name: "Barbell Thruster",
    equipment: "BARBELL",
    movement: "SQUAT",
    category: "Full Body",
    region: "Full body",
    isCompound: true,
  },
  {
    name: "Dumbbell Thruster",
    equipment: "DUMBBELL",
    movement: "SQUAT",
    category: "Full Body",
    region: "Full body",
    isCompound: true,
  },
  {
    name: "Kettlebell Clean and Press",
    equipment: "KETTLEBELL",
    movement: "HINGE",
    category: "Full Body",
    region: "Full body",
    isCompound: true,
  },
  {
    name: "Kettlebell Goblet Squat",
    equipment: "KETTLEBELL",
    movement: "SQUAT",
    category: "Full Body",
    region: "Lower body",
    isCompound: true,
  },
  {
    name: "Turkish Get-Up",
    equipment: "KETTLEBELL",
    movement: "ROTATION",
    category: "Full Body",
    region: "Full body",
    isCompound: true,
  },
  {
    name: "Burpee",
    equipment: "BODYWEIGHT",
    movement: "SQUAT",
    category: "Full Body",
    region: "Full body",
    isCompound: true,
  },
  {
    name: "Bear Crawl",
    equipment: "BODYWEIGHT",
    movement: "CARRY",
    category: "Full Body",
    region: "Full body",
    isCompound: true,
  },
  {
    name: "Suitcase Carry",
    equipment: "DUMBBELL",
    movement: "CARRY",
    category: "Full Body",
    region: "Core and grip",
    isCompound: true,
  },
  {
    name: "Overhead Carry",
    equipment: "DUMBBELL",
    movement: "CARRY",
    category: "Full Body",
    region: "Shoulders and core",
    isCompound: true,
  },
];

export const exerciseCategories = [
  "Chest",
  "Back",
  "Shoulders",
  "Biceps",
  "Triceps",
  "Quadriceps",
  "Hamstrings",
  "Glutes",
  "Calves",
  "Abs",
  "Traps",
  "Forearms",
  "Full Body",
] as const;

export type ExerciseCategory = (typeof exerciseCategories)[number];
